baseURL = "https://juan.benet.ai/"
languageCode = "en-us"
canonifyURLs = false
relativeURLs = true

pygmentsCodeFences = true
pygmentsUseClasses = true

title = "jbenet's blog"
name = "jbenet's blog"
description = "a blog"

[markup.goldmark.renderer]
unsafe = true
